### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.0] Physical types of damage

### ISSUE THREAD

**Issue by PT63x4** [sovietspaceship/souls-bug-reports#36]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Is your feature request related to a problem? Please describe.**
The feature that I request is related to clarifying the type of physical damage a weapon does, since some of the weapons are vague by their design in explaining what type of physical damage they do.

**Describe the solution you'd like**
Add the type of physical damage the weapons do between the type of weapon it is (ie: Greatswords, Katanas) , and their ash of war, that being in either side of the marked in the image.
![PhyDamage](https://github.com/sovietspaceship/souls-bug-reports/assets/164861098/e306d808-05ab-48f6-b4ba-ad8fcbf86879)

**Comment by sovietspaceship** [comment]
damage type per weapon is sometimes misleading or incorrect in the game ui. The only way right now in the build planner is to use the damage calculator and select each attack like this

![image](https://github.com/sovietspaceship/souls-bug-reports/assets/100027345/d70ba6b0-11b6-47b5-89c1-a0509a2589b3)

I might add something to the weapon tooltips to show damage type based on attack data rather than the value displayed in-game

**Comment by sovietspaceship** [comment]
done
